### ISSUE TITLE
Gambit 2.2.0 Tutorial/MDMSM  model comling failed

### ISSUE THREAD

**Issue by yuanfangtardis** [GambitBSM/gambit_2.2#1]
Dear GUM authors,
      I am very interested in your GUM　program and installed Gambit_2.2.0 on my Ubuntu_18.04 machine。 
      I tested your   MDMSM in Tutorial and run gum sucessfuly   . But I found I cannot compile new model in GAMBIT /build  dir. 
      Here  are how I tested :

       1. In Gum directory, type
                 
                cd Modes/; mkdir MDMSM;
                 cd ../ ; 
                 ./gum -f Tutorial/MDMSM.gum 

        2. Then change to Gambit  main directory:
                 
                 cd ..  ; mkdir build;  cd build ;
                 cmake -DWITH_AXEL=ON -DWITH_HEPMC=ON -DWITH_ROOT=ON -DWITH_MPI=ON ../
                 make

         then I get these errors:
                
            Scanning dependencies of target SpecBit
[ 11%] Building CXX object SpecBit/CMakeFiles/SpecBit.dir/src/SpecBit_types.cpp.o
[ 11%] Building CXX object SpecBit/CMakeFiles/SpecBit.dir/src/SpecBit_ScalarSingletDM.cpp.o
[ 11%] Building CXX object SpecBit/CMakeFiles/SpecBit.dir/src/SpecBit_MDMSM.cpp.o
In file included from /home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:29:0:
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:99:29: error: ‘MDMSM’ in namespace ‘Gambit::SpectrumContents’ does not name a type
   typedef SpectrumContents::MDMSM Contents;
                             ^~~~~
In file included from /home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec.hpp:27:0,
                 from /home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/SMSimpleSpec.hpp:20,
                 from /home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spectrum_factories.hpp:20,
                 from /home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:21:
/home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec_head.hpp: In instantiation of ‘class Gambit::Spec<Gambit::Models::MDMSMSimpleSpec>’:
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/SLHASimpleSpec.hpp:64:13: required from ‘class Gambit::SLHASimpleSpec<Gambit::Models::MDMSMSimpleSpec>’
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:105:34: required from here
/home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec_head.hpp:105:51: error: no type named ‘Contents’ in ‘struct Gambit::SpecTraits<Gambit::Models::MDMSMSimpleSpec>’
          typedef typename SpecTraits<D>::Contents Contents;
                                                   ^~~~~~~~
In file included from /home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:29:0:
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:126:31: error: ‘MDMSM’ in namespace ‘Gambit::SpectrumContents’ does not name a type
       const SpectrumContents::MDMSM contents;
                               ^~~~~
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp: In member function ‘virtual void Gambit::Models::MDMSMSimpleSpec::add_to_SLHAea(int, SLHAea::Coll&) const’:
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:136:47: error: ‘contents’ was not declared in this scope
         add_SimpleSpec_to_SLHAea(*this, slha, contents);
                                               ^~~~~~~~
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:136:47: note: suggested alternative: ‘Contents’
         add_SimpleSpec_to_SLHAea(*this, slha, contents);
                                               ^~~~~~~~
                                               Contents
/home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp: In function ‘void Gambit::SpecBit::fill_map_from_MDMSM_spectrum(std::map<std::__cxx11::basic_string<char>, double>&, const Gambit::Spectrum&)’:
/home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:161:38: error: ‘MDMSM’ in namespace ‘Gambit::SpectrumContents’ does not name a type
       static const SpectrumContents::MDMSM contents;
                                      ^~~~~
/home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:162:73: error: ‘contents’ was not declared in this scope
       static const std::vector<SpectrumParameter> required_parameters = contents.all_parameters();
                                                                         ^~~~~~~~
/home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:162:73: note: suggested alternative: ‘long_nt’
       static const std::vector<SpectrumParameter> required_parameters = contents.all_parameters();
                                                                         ^~~~~~~~
                                                                         long_nt
In file included from /home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec.hpp:27:0,
                 from /home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/SMSimpleSpec.hpp:20,
                 from /home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spectrum_factories.hpp:20,
                 from /home/yyf/yfgum/gambit_2.2/SpecBit/src/SpecBit_MDMSM.cpp:21:
/home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec_head.hpp: In instantiation of ‘Gambit::Spec< <template-parameter-1-1> >::Spec() [with DerivedSpec = Gambit::Models::MDMSMSimpleSpec]’:
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/SLHASimpleSpec.hpp:90:35: required from ‘Gambit::SLHASimpleSpec<Derived>::SLHASimpleSpec(const SLHAea::Coll&) [with Derived = Gambit::Models::MDMSMSimpleSpec]’
/home/yyf/yfgum/gambit_2.2/Models/include/gambit/Models/SimpleSpectra/MDMSMSimpleSpec.hpp:112:30: required from here
/home/yyf/yfgum/gambit_2.2/Elements/include/gambit/Elements/spec_head.hpp:205:51: error: no type named ‘Contents’ in ‘struct Gambit::SpecTraits<Gambit::Models::MDMSMSimpleSpec>’
          Spec() { static VerifyContents<Contents> runonce(*this); };
                                                   ^~~~~~~
SpecBit/CMakeFiles/SpecBit.dir/build.make:110: recipe for target 'SpecBit/CMakeFiles/SpecBit.dir/src/SpecBit_MDMSM.cpp.o' failed
make[2]: *** [SpecBit/CMakeFiles/SpecBit.dir/src/SpecBit_MDMSM.cpp.o] Error 1
CMakeFiles/Makefile2:20547: recipe for target 'SpecBit/CMakeFiles/SpecBit.dir/all' failed
make[1]: *** [SpecBit/CMakeFiles/SpecBit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I  tired the same procedure in gambit_2.1.2  it worked fine, no errors.   
 Besides, I also tried to compile Gambit_2.2.0 directly without running gum, it also worked well, no errors.  
Could you please  help me? Thank you in advance. 
My output files are attached.  If you need more information ,please contact me.

**Comment by tegonzalo** [comment]
Hello Yuanfang. 

Sorry the late reply and thanks for bringing up this issue. I have confirmed that this is a problem. I have fixed it and pushed it as 2.2.1 to this fork. Please test now and let me know if it's ok.

Best,
Tomas

**Comment by tegonzalo** [comment]
Hello again Yuanfang,

Did you have time to test if the error went away with the new version? Let me know so we can close this issue.

Best,
Tomas

**Comment by yuanfangtardis** [comment]
> Hello again Yuanfang,
> 
> Did you have time to test if the error went away with the new version? Let me know so we can close this issue.
> 
> Best, Tomas

sorry for the late reply. I did not loginto github recently. I will test it and give the reply today or tommorrow.

**Comment by yuanfangtardis** [comment]
> Hello again Yuanfang,
> 
> Did you have time to test if the error went away with the new version? Let me know so we can close this issue.
> 
> Best, Tomas

Dear Tomas,
   I  tested the new version and found everything works fine! Thank you very much.

Best,
Yuanfang

**Comment by tegonzalo** [comment]
Great! I will close this issue then.
